### ISSUE TITLE
Is the name cascading animation clear?

### ISSUE THREAD

**Issue by JerryNixon** [JerryNixon/PathAnimation#2]
We might need to consider if the name clearly inspires usage.

**Comment by nekgiannoulis** [comment]
I agree that the name is not clear enough.

Let's discuss the base usage of this control:
- You specify duration and starting values for opacity, scale and translation (more to come).
- You specify when the next element will start the animation (TimeSpan).
- You call start and all elements are animated one after another. 

All elements are animated from starting values to their defaults, but in the future, we will also be able to specify end values. For example, StartColor=Black, EndColor=Red, ColorDuration: 1 second.

Currently, you can set a path (that contains text) and control will analyze it, splitting and applying animations to each letter. Alternatively, you can directly set any UIElement to xaml, and it will animate them the same way.

So, it might can be named successive, repeated or something similar.

**Comment by JerryNixon** [comment]
One control at a time. Let’s get PathAnimation perfect and socialized. And see how that goes before you spend too much time on another. I know you are likely having a great time writing this, so you can do whatever you want. But let’s focus on one thing at a time. Maybe break the controls into different libraries, too. What do you thnk?

**Comment by nekgiannoulis** [comment]
Makes sense. Let's focus on path animations and we can discuss later details about this one.
