### ISSUE TITLE
Boolean versus ENUM

### ISSUE THREAD

**Issue by JerryNixon** [JerryNixon/PathAnimation#3]
I think many of our custom properties that are Boolean should be ENUM. 

For example OrientToPath, consider this (for the purpose of making the API usage obvious)

    public Orientations ItemOrientation { get; set; }
    public enum Orientations {
        None,
        ToPath,
        ToPathReversed,
        Vertical,
        VerticalReversed,
    }

With it we can delete OrientToPath, MoveVertically, and FlipItems without losing any functionality. Since these items are already mutually exclusive. Does this make any sense? 

Consider this, too

    // change this to standard types
    public Visibility PathVisibility { get; set; }

    // rename these to more clear names
    public double TranslationSmoothing { get; set; }
    public double RotationSmoothing { get; set; }

    // like orientation, use ENUM
    public Behaviors StartBehavior { get; set; }
    public Behaviors EndBehavior { get; set; }
    public enum Behaviors {
        Default,
        Stack
    }

We still may not have the API quite right. But this will be a nice tweak.

**Comment by nekgiannoulis** [comment]
With regards to Orientations enum, there are actually 4 options for specifying children orientation and one for rotating them. So, we have in total 8 options.

One approach is to have 4 enum values and one boolean

```
public bool OrientToPath { get; set; }
public Orientations ItemOrientation { get; set; }
public enum Orientations {    
    ToPath, //or Horizontal
    ToPathReversed, //or HorizontalReversed
    Vertical,
    VerticalReversed
}
```

and another to have 8 enum values. Something like:

```
public Orientations ItemOrientation { get; set; }
public enum Orientations {    
    Horizontal,
    HorizontalReversed,
    Vertical,
    VerticalReversed,
    FollowHorizontally,
    FollowHorizontallyReversed,
    FollowVertically,
    FollowVerticallyReversed
}
```

Both ways, programmer can specify that elements are facing to one direction and are not rotating.

**Comment by nekgiannoulis** [comment]
Regarding properties renaming, we also have to consider that we have some attached properties that override LayoutPath properties.

In the following example, taken from current implementation,

```
<LayoutPath  SmoothTranslation="5">
         <Path x:Name="child1" />
         <Path x:Name="child2" LayoutPath.ChildSmoothTranslation="3" />
</LayoutPath>
```

SmoothTranslation is a dependency property and ChildSmoothTranslation is an attached dependency property, both declared in LayoutPath.cs

With that in mind, new names can be

```
//property
public double TranslationSmoothing { get; set; }
//attached property
public double TranslationSmoothingOverride { get; set; }
```

I don't know if there is an existing naming convention for this scenario. If yes, let me know.

**Comment by JerryNixon** [comment]
Not override, as that has a specific OOP meaning. Maybe “Local” would be a better suffix or the other could have “Default”. Something like this:

public double SmoothingDefault;
public double Smoothing;

Yeah, I think default implies that everything will get it unless a local value is set. I am not saying to make this change yet. Just asking your opinion first.

**Comment by JerryNixon** [comment]
Thinking out loud here. But, I like a longer set of ENUM options than multiple properties. Especially if “reversed” is all we are adding. I think it makes sense and isn’t needlessly complicated. That being said, is there a way to simplify it further?

**Comment by nekgiannoulis** [comment]
I like the "Default" suffix, it is more clear. So, let's go this way.

Well, we can always leave 5 options `{ None, ToPath, ToPathReversed, Vertical, VerticalReversed }` and let user choose _None_ for not rotating children and apply a rotate / flip transform to each child individually.

Otherwise, I think we have to use 8 ENUM values.

**Comment by JerryNixon** [comment]
That’s a huge improvement.

**Comment by nekgiannoulis** [comment]
I just finished with the changes discussed on this issue:
- Enumerations are used instead of boolean properties.
- Some properties renamed to more clear names.

Note that Progress property renamed to PathProgress and Progress is now used for the attached property. 
I didn't choose the name ProgressDefault because it does not apply the same progress to all children.
